// src/constants/permissions.js
module.exports = {
  // User
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  VIEW_USER: "VIEW_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",

  // Branch
  CREATE_BRANCH: "CREATE_BRANCH",
  VIEW_BRANCH: "VIEW_BRANCH",
  APPROVE_BRANCH_CHANGE: "APPROVE_BRANCH_CHANGE",

  // Student
  REGISTER_STUDENT: "REGISTER_STUDENT",
  VIEW_STUDENT: "VIEW_STUDENT",
  SUSPEND_STUDENT: "SUSPEND_STUDENT",

  // Teacher
  REGISTER_TEACHER: "REGISTER_TEACHER",
  VIEW_TEACHER: "VIEW_TEACHER",

  // Class
  CREATE_CLASS: "CREATE_CLASS",
  VIEW_CLASS: "VIEW_CLASS",

  // Attendance
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",

  // Exam
  CREATE_EXAM: "CREATE_EXAM",
  GRADE_EXAM: "GRADE_EXAM",
  VIEW_EXAM: "VIEW_EXAM",

  // Finance
  VIEW_FINANCIAL_REPORT: "VIEW_FINANCIAL_REPORT",

  // Communication
  SEND_MESSAGE: "SEND_MESSAGE",
  VIEW_ANNOUNCEMENT: "VIEW_ANNOUNCEMENT",
  PUBLISH_ANNOUNCEMENT: "PUBLISH_ANNOUNCEMENT",

  // System / Policy
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  MANAGE_POLICIES: "MANAGE_POLICIES",
  APPROVE_CHANGES: "APPROVE_CHANGES",
};
